// Rotas onde os fluxos guiados se aplicam. O match com o pathname é feito por
// `matchRoute` (em ./index), que suporta segmentos dinâmicos do Next (ex.: [id]).
export const FLOW_ROUTES = {
  dashboard: "/dashboard",
  routines: "/routines",
  routineDay: "/routines/[date]",
  orders: "/orders",
  orderDetail: "/orders/[id]",
  clients: "/clients",
  clientDetail: "/clients/[id]/overview",
  clientVisits: "/clients/[id]/visits",
  clientStock: "/clients/[id]/stock",
  clientScore: "/clients/[id]/score",
  clientFactories: "/clients/[id]/factories",
  clientOrders: "/clients/[id]/orders",
  factories: "/factories",
  factoryDetail: "/factories/[id]/overview",
  factoryProducts: "/factories/[id]/products",
  factoryPrices: "/factories/[id]/price-lists",
  priceListDetail: "/factories/[id]/price-lists/[priceListId]",
  productDetail: "/factories/[id]/products/[productId]",
  factorySellers: "/factories/[id]/sellers",
  factoryClients: "/factories/[id]/clients",
  factoryOrders: "/factories/[id]/orders",
  factoryImportTemplate: "/factories/[id]/import-template",
  users: "/users",
  sellers: "/sellers",
  sellerDetail: "/sellers/[id]",
  settings: "/settings",
  settingsCatalog: "/settings/catalog",
  settingsRoutine: "/settings/routine",
  profile: "/profile",
} as const;
